#!/usr/bin/env bash

# This script contains the kubeconfig and SSH private key for accessing
# the cluster student-sgnl (student-02).

# Running the script saves the kubeconfig and SSH private key to files
# in the current working directory.
# Alternatively, you can copy the contents of the files from below
# and save them manually to an appropriately named file.
# After saving the files, set the KUBECONFIG environment variable to
# point to the kubeconfig file to interact with the cluster using kubectl.
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpJd01UVTNNVE13SGhjTk1qVXhNVEF4TVRZME9ETXpXaGNOTXpVeE1ETXdNVFkwT0RNegpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpJd01UVTNNVE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUdUIrMHBuaEtRMHVnaWk3QU0yQjFkNGpFVkN1SFpSbEw4azZYUVFvT0MKYVhIdHFVY1hTQXd3b3dnVjBLdUpPRmZBRkxiaFBWbUd2Nno3RW1TM00wLzBvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXVxRWdvUzBWYzJQOWxpV2ZWUWFkCmVyQnI3RlF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnWjJCUUVJT2RkbmxKWFUrU1BpYnd0Z216alpDcDdhVUcKTWdHbUNMMDNtWkVDSVFDSmgwdTBmbWEyamhHQmphZE5ydzhwT1gza0dWK0Yyc2xqNndQSXVLeXd0dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://141.72.176.108:6443
  name: student-sgnl
contexts:
- context:
    cluster: student-sgnl
    user: student-sgnl
  name: student-sgnl
current-context: student-sgnl
kind: Config
users:
- name: student-sgnl
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJRDcyR3IwTkNvZ1F3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOell5TURFMU56RXpNQjRYRFRJMU1URXdNVEUyTkRnek0xb1hEVEkyTVRFdwpNVEUyTkRnek0xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJMUi93a0U5ek5mbmZBUEcKNUJ5T2ZGakRvYXhRWGR1TElPM0lqM3QyVExkZy9MUDUxSlZmV3gwRU9YVmFady91dXcrdklCRXNkZ1VpVStETwpGa1JYSmJPalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU091Q1h5SkI0d2MwZUMxVTYxNWMzci9LNW8wakFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQTh5KzZHZElVQnIrdzNLaGNkTDkwaWFFdXROanpDMTFyOTRZZXh0Qjh2YjRDSVFEV2RJVDg5WDhnQ1N2bwpydWIydlVUSEZ3eVZaWElsdzU2bHJmN1dlNmNOa2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZURDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM05qSXdNVFUzTVRNd0hoY05NalV4TVRBeE1UWTBPRE16V2hjTk16VXhNRE13TVRZME9ETXoKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM05qSXdNVFUzTVRNd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUjlaNnZOUjQ3N0VoN095Y1o0VXNObG9mbDNBNWk1WktPZU9MTmtNMVJBCml2cE5QTlVIOHNIUUhObWNWNzdIbHZUdVVvVnFnOXdudUovQlBKdVRRWnVobzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVqcmdsOGlRZU1ITkhndFZPdGVYTgo2L3l1YU5Jd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFKUVpkMEJCZ0ZLcmUybzEwekRTclA1N3MvQm5aR2hPCkdidGV3L3NuQWF0NUFpRUF2VTRyUXNER215MXcrM1p3NVNHMDlaZzJKbGwza2pUMy96a3lxZG5kaFhrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUQ0TzlLMFI5dDU1YytYb0JWblVpbjlnT2o4QTY0S2E0Zk5OZkNRQmlhNHRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdEgvQ1FUM00xK2Q4QThia0hJNThXTU9ockZCZDI0c2c3Y2lQZTNaTXQyRDhzL25VbFY5YgpIUVE1ZFZwbkQrNjdENjhnRVN4MkJTSlQ0TTRXUkZjbHN3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
